# Generated by Django 4.2.4 on 2024-02-10 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(upload_to='brands', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='products', verbose_name='Image')),
                ('price', models.FloatField(verbose_name='Price')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('flag', models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, verbose_name='Flag')),
                ('flag_en', models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, null=True, verbose_name='Flag')),
                ('flag_ar', models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, null=True, verbose_name='Flag')),
                ('sku', models.CharField(max_length=12, verbose_name='Sku')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_ar', models.CharField(max_length=300, null=True, verbose_name='Subtitle')),
                ('description', models.TextField(max_length=40000, verbose_name='Description')),
                ('description_en', models.TextField(max_length=40000, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(max_length=40000, null=True, verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brand', verbose_name='Brand')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('review', models.CharField(max_length=300, verbose_name='Review')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_auther', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='Product')),
            ],
        ),
    ]
