# Generated by Django 4.2.4 on 2023-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, verbose_name='Flag'),
        ),
    ]
