# Generated by Django 4.2.4 on 2023-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=3, verbose_name='Rate'),
            preserve_default=False,
        ),
    ]
