# Generated by Django 4.2.4 on 2025-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_to_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=100, verbose_name='Max Quantity'),
        ),
    ]
