# Generated by Django 4.2.4 on 2024-01-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='product.brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(max_length=40000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=40000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_ar',
            field=models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, null=True, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='flag_en',
            field=models.CharField(choices=[('sale', 'sale'), ('new', 'new'), ('feature', 'feature')], max_length=10, null=True, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ar',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_ar',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_en',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Subtitle'),
        ),
    ]
