# Generated by Django 4.2.4 on 2024-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_brand_ar_product_brand_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_en',
        ),
        migrations.AddField(
            model_name='review',
            name='review_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Review'),
        ),
    ]
