# Generated by Django 4.2.4 on 2024-01-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_brand_ar_remove_product_brand_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_ar',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_en',
        ),
    ]
