# Generated by Django 4.2.4 on 2024-01-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_review_review_ar_remove_review_review_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Review'),
        ),
    ]
