# Generated by Django 4.2.4 on 2024-01-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_review_ar_review_review_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_ar',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_en',
        ),
    ]
