# Generated by Django 4.2.4 on 2023-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='8XGKG8B9', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered'), ('Processed', 'Processed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
