# Generated by Django 4.2.4 on 2024-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='K82Z9X2G', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Processed', 'Processed'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered')], default='Recieved', max_length=10),
        ),
    ]
