# Generated by Django 4.2.4 on 2024-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='2SM1QMXY', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered'), ('Processed', 'Processed')], default='Recieved', max_length=10),
        ),
    ]
