# Generated by Django 4.2.4 on 2024-03-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cart_status_alter_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='KKOWCCDZ', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped')], default='Recieved', max_length=10),
        ),
    ]
