# Generated by Django 4.2.4 on 2024-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_cart_status_alter_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='PTZSN9WK', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Recieved', 'Recieved'), ('Delivered', 'Delivered')], default='Recieved', max_length=10),
        ),
    ]
