# Generated by Django 4.2.4 on 2024-09-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_cart_status_alter_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='7VYNF4GE', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Recieved', 'Recieved'), ('Processed', 'Processed'), ('Delivered', 'Delivered')], default='Recieved', max_length=10),
        ),
    ]
