# Generated by Django 4.2.4 on 2025-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='KGB7ILZI', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Recieved', 'Recieved')], default='Recieved', max_length=10),
        ),
    ]
